# Q.1 Matrix Operations

### Given the matrix `gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')`, perform the following operations:

- **i. Sum of all elements** in the matrix.
- **ii. Sum of all elements row-wise**.
- **iii. Sum of all elements column-wise**.


In [1]:
import numpy as np

In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

print("Sum of all elements:", gfg.sum())
print("Sum of all rows:", gfg.sum(axis=1))
print("Sum of all columns:", gfg.sum(axis=0))

Sum of all elements: 45
Sum of all rows: [[14]
 [16]
 [15]]
Sum of all columns: [[20  9 16]]


# Q.2 Array Operations

### (a) Given the array `array = [10, 52, 62, 16, 16, 54, 453]`, perform the following operations:

- **i. Sorted array**  
- **ii. Indices of sorted array**  
- **iii. 4 smallest elements**  
- **iv. 5 largest elements**  

---

### (b) Given the array `array = [1.0, 1.2, 2.2, 2.0, 3.0, 2.0]`, perform the following operations:

- **i. Extract integer elements only**  
- **ii. Extract float elements only**  


In [2]:
#a
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted Array:", np.sort(array))
print("Indices of Sorted Array:", np.argsort(array))
print("4 Smallest Elements:", np.sort(array)[:4])
print("5 Largest Elements:", np.sort(array)[-5:])

Sorted Array: [ 10  16  16  52  54  62 453]
Indices of Sorted Array: [0 3 4 1 5 2 6]
4 Smallest Elements: [10 16 16 52]
5 Largest Elements: [ 16  52  54  62 453]


In [3]:
#b
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

print("Integer Elements Only:", array[np.floor(array) == array])
print("Float Elements Only:", array[np.floor(array) != array])

Integer Elements Only: [1. 2. 3. 2.]
Float Elements Only: [1.2 2.2]


# Q.3 Weekly Sales Dataset with NumPy Broadcasting

### a) Generate your unique sales dataset:
- Take the sum of the **ASCII values** of the initials of your **first and last name**.  
  - Example: If your initials are **A B** → ASCII sum = `65 + 66 = 131`  
  - Compute **sales** as:
    ```python
    sales = np.array([X, X+50, X+100, X+150, X+200])
    ```

---

### b) Compute your personalized tax rate:
- Formula:  Tax Rate = ((X % 5) + 5) / 100
- Use **NumPy broadcasting** to apply this tax rate to each sales value.

---

### c) Adjust sales based on discounts:
- **Apply a 5% discount** if `sales < X+100`  
- **Apply a 10% discount** if `sales >= X+100`

---

### d) Expand sales data for multiple weeks:
- Create a **3×5 matrix** representing **three weeks of sales** by stacking `sales` three times.
- Increase sales by **2% per week** using **element-wise broadcasting**.

---


In [4]:
#a
X = ord('S') + ord('N')
sales = np.array([X, X+50, X+100, X+150, X+200])
print(sales)

[161 211 261 311 361]


In [5]:
#b
tax_rate = ((X % 5) + 5) / 100
tax = sales * tax_rate
print(tax)

[ 9.66 12.66 15.66 18.66 21.66]


In [6]:
#c
discount = np.where(sales < X+100, 0.05, 0.10)
discounted = sales * (1 - discount)
print(discounted)

[152.95 200.45 234.9  279.9  324.9 ]


In [7]:
#d
weekly_sales = np.tile(discounted, (3, 1))
multiplier = np.array([1.00, 1.02, 1.04]).reshape(3, 1)
adjusted = weekly_sales * multiplier
print(adjusted)

[[152.95  200.45  234.9   279.9   324.9  ]
 [156.009 204.459 239.598 285.498 331.398]
 [159.068 208.468 244.296 291.096 337.896]]


# Q4. Plotting Mathematical Functions Using NumPy and Matplotlib

### **Step 1: Generate x values**
- Use `np.linspace()` to create **100 points** between **-10 and 10**.

---

### **Step 2: Compute y values using NumPy**
- Compute values for the following functions:
  - \( Y = x^2 \)
  - \( Y = sin(x) \)
  - \( Y = e^x \)
  - \( Y = log(|x| + 1) \)

---

### **Step 3: Plot the functions using Matplotlib**
- Plot each of the functions.
- Add:
  - **Title**: `"Plots of Mathematical Functions"`
  - **X-axis Label**: `"X values"`
  - **Y-axis Label**: `"Y values"`
  - **Grid** for clarity.


In [11]:
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(-10, 10, 100)
y1 = x ** 2
y2 = np.sin(x)
y3 = np.exp(x)
y4 = np.log(np.abs(x) + 1)
fig, axes = plt.subplots(2, 2, figsize=(12, 8))

axes[0, 0].plot(x, y1, color='b', label="Y = x²")
axes[0, 0].set_title("Y = x²")
axes[0, 0].set_xlabel("X values")
axes[0, 0].set_ylabel("Y values")
axes[0, 0].legend()
axes[0, 0].grid(True)

axes[0, 1].plot(x, y2, color='g', label="Y = sin(x)")
axes[0, 1].set_title("Y = sin(x)")
axes[0, 1].set_xlabel("X values")
axes[0, 1].set_ylabel("Y values")
axes[0, 1].legend()
axes[0, 1].grid(True)

axes[1, 0].plot(x, y3, color='r', label="Y = e^x")
axes[1, 0].set_title("Y = e^x")
axes[1, 0].set_xlabel("X values")
axes[1, 0].set_ylabel("Y values")
axes[1, 0].legend()
axes[1, 0].grid(True)

axes[1, 1].plot(x, y4, color='purple', label="Y = log(|x| + 1)")
axes[1, 1].set_title("Y = log(|x| + 1)")
axes[1, 1].set_xlabel("X values")
axes[1, 1].set_ylabel("Y values")
axes[1, 1].legend()
axes[1, 1].grid(True)

plt.suptitle("Plots of Mathematical Functions", fontsize=16)

plt.tight_layout()
plt.show()


ModuleNotFoundError: No module named 'matplotlib'